version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    target-branch: develop
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    target-branch: main
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
