import { GOOGLE_TEXT_FONTS, GOOGLE_TEXT_FONT_WEIGHTS } from './googleFonts';

export const TEXT_FONT_FAMILY_OPTIONS: string[] = [...GOOGLE_TEXT_FONTS];
export const TEXT_FONT_WEIGHT_OPTIONS: string[] = [...GOOGLE_TEXT_FONT_WEIGHTS];

export const DEFAULT_TEXT_FONT_FAMILY = GOOGLE_TEXT_FONTS[0];
export const DEFAULT_TEXT_FONT_WEIGHT = GOOGLE_TEXT_FONT_WEIGHTS[1];
