name: CD

on:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  client:
    name: Deploy (frontend)
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install -g vercel@latest
      - run: vercel pull --yes --environment production --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      - run: vercel build --yes --target production --token ${{ secrets.VERCEL_TOKEN }}
      - run: vercel deploy --yes --target production --prebuilt --token ${{ secrets.VERCEL_TOKEN }}

  server:
    name: Deploy (backend)
    runs-on: ubuntu-latest
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'dev' }}
    steps:
      - run: curl --request POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
